wandb_version: 1

learning_rate:
  desc: null
  value: 5.0e-05
architecture:
  desc: null
  value: SPINDLE
dataset:
  desc: null
  value: SPINDLE
epochs:
  desc: null
  value: 10
_wandb:
  desc: null
  value:
    python_version: 3.9.18
    cli_version: 0.17.3
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1720021347
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 53
      - 55
      3:
      - 16
      - 23
      4: 3.9.18
      5: 0.17.3
      8:
      - 5
      13: linux-x86_64
